### PR TITLE
Use `TradeBalance` to get the combined balance of all currencies

### PR DESCRIPTION
**Pull request by Shourai**
Since the button `ALL` gets the total balance, it's convoluted to go through all the currencies and
multiply it by the current price.
Using `TradeBalance` is much easier, this avoids getting errors when you have currencies that do not trade to `trade_to_currency` e.g. Dogecoin.

Also added if statements to get BCH to show its values

### CODE REVIEW

**Comment by Endogen** [comment]
First of all, thanks for the PR! I actually already thought about using `TradeBalance` and had it implemented but dismissed it because:
1. Getting the value of a specific coin should use the same basic logic as getting the value of all coins. Since i couldn't get the value of a single coin directly from Kraken, i had to calculate it and then ended up using that also for the value of all coins.
2. I kind of don't like the way the value is calculated by using `TradeBalance`. This is what it does: `Rates used for the floating valuation is the midpoint of the best bid and ask prices`. This is not a real value - or at least it's not as real as a value that is calculated by the last trade price. The last trade really happened, but the midpoint of the best bid and ask price is just theoretical.
3. It's possible for the value that is coming from `TradeBalance` to vary a lot. Much more then the value derived from the last trade price.

That's why i didn't use it. What do you say about these arguments? Any thoughts on that?

> this avoids getting errors when you have currencies that do not trade to trade_to_currency e.g. Dogecoin.

That's of course an argument. I will think about it but i could also fix that while using the way it already works. It's just not as easy as calling `TradeBalance` :) Will think about it.

**Comment by Shourai** [comment]
This bot is a great substitute and I enjoy using it!
A shame that Kraken does not have their own app.
 I haven't checked the one on iOS, but I read it has hardly any features.

To give an answer on your points:

1. Unfortunately there is not an option to get the value of single coins, so your option of calculating is the way to go. I agree that the most accurate way to get the total value would be doing the calculation for each coin.
2. By doing a rough calculation and comparing with `TradeBalance`,  the price varies by one promille between the two. (Could you double check this? At least during the time I checked, maybe the midpoint lies quite near the last trade price)
Though someone with a very large wallet would see some discrepancy. But I would assume for most people we are talking about cents.
3. I would assume this could happen when you have huge buy/sell spikes in a short burst. However, these spikes usually occur only with one coin. When this is the case it would be more interesting for the user to follow that individual coin value than to check upon the total balance. Neither way of getting the total balance would help the user determine which coin is being affected, only that _something_ is going on.

Catching all the coins in a switch statement would be more effort than it is worth.
These are coins which do not have `trade_to_currency` options (for USD & EUR):

- EOS
- ICN
- GNO
- XLM
- MLN 
- REP (no USD, does have EUR)
- and of course the beloved XDG.

**Comment by Endogen** [comment]
I thought about it and came to the conclusion that it's not worth the effort to do it the way i wanted to do it. It would be to complicated.

So i'm accepting your PR but i will change it a little to clean it up. Thanks to bring up the issue that there are coins that do not trade to a "real" currency.

**Comment by Endogen** [comment]
The consequence is that the value of a single coin is not calculated the same way as the value of all coins that are owned.

**Pull request merged**
